### ISSUE TITLE
Request to add a speed dial/ option

### ISSUE THREAD

**Issue by parachataha** [Anikalp1/Sorting_Visualizer#1]
Hey, love the app. Would be great to add a setting to speed up the visualiser by some scale factors, eg x0.5, x1, x1.5, x2, x2.5, x3, x3.5, x4

Cheers!
Thanks

**Comment by Anikalp1** [comment]
Go for it. Do attach a demo of final working after updates. 
Will check your PR.

**Comment by JustFossa** [comment]
@Anikalp1 u can close this ig

**Comment by Anikalp1** [comment]
Yeah, as of now this issue is closed.
